# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

# sudo: false
# language: python
# virtualenv:
#   system_site_packages: true
# env:
#   matrix:
#     - DISTRIB="ubuntu" PYTHON_VERSION="2.7" COVERAGE="true"
#     - DISTRIB="conda" PYTHON_VERSION="2.7" COVERAGE="false"
#     - DISTRIB="conda" PYTHON_VERSION="3.3" COVERAGE="false"
#     - DISTRIB="conda" PYTHON_VERSION="3.4" COVERAGE="false"
# addons:
#   apt:
#     packages:
#       - git
#       - python-pip
# install:
#   - source tests/travis_install.sh
#   - pip install -r requirements.txt
# before_script:
#   - git config --global user.email "you@example.com"
#   - git config --global user.name "Your Name"
# script:
#   - python setup.py test
# after_success:
#   - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
# cache:
#   - apt


language: python
python:
- '3.6'

install:
- pip install -r requirements.txt
#- echo "import nltk; nltk.download('punkt')" | python twotebotapi/manage.py shell

script:
- python manage.py test twote/bot_utils/
#- python twote/manage.py test twotebotapi/twotebotapp/

before_install:
